// AUTO-GENERATED by build.rs from tools.toml — do not edit
#![allow(clippy::all)]
#[rustfmt::skip]

pub fn generated_tool_list() -> serde_json::Value {
serde_json::from_str(r##"{
  "tools": [
    {
      "description": "Search and retrieve context entries relevant to the current task. Primary retrieval tool. Combines FTS5 keyword search with scope resolution (ancestor walk). Call after receiving a task with a summary of what you are working on. When query is omitted, returns all entries at the target scope via ancestor walk. Returns metadata + snippet for two-phase retrieval; use cx_get for full body. IMPORTANT: The query uses FTS5 with implicit AND between words. Use 1-3 keywords, not full sentences. More words = fewer results. Examples: 'auth migration' (good), 'how does the authentication migration work' (too many words, likely 0 results). Use OR for alternatives: 'auth OR authentication'. Use prefix matching: 'migrat*'.",
      "inputSchema": {
        "properties": {
          "kinds": {
            "description": "Filter to specific entry kinds (OR logic). Valid values: fact, decision, preference, lesson, reference, feedback, pattern, observation.",
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "limit": {
            "description": "Maximum number of entries to return. Default: 20, max: 200.",
            "type": "integer"
          },
          "max_tokens": {
            "description": "Maximum token budget for the response. Results are trimmed to fit within this budget, prioritizing higher-relevance entries. Uses ~4 chars/token estimation.",
            "type": "integer"
          },
          "query": {
            "description": "FTS5 search query. Use 1-3 keywords (implicit AND). Do NOT pass full sentences. Supports prefix queries (rust*), phrase queries (\"scope path\"), and boolean operators (AND, OR, NOT). Use OR between synonyms: 'auth OR authentication'. Omit to return all entries at the target scope via ancestor walk.",
            "type": "string"
          },
          "scope": {
            "description": "Scope path to search within. Retrieves entries from this scope and all ancestor scopes. Example: 'global/project:helioy/repo:nancyr' also searches 'global/project:helioy' and 'global'. Default: 'global'.",
            "type": "string"
          },
          "tags": {
            "description": "Filter to entries with any of these tags (OR logic). Pass a JSON array: [\"tag1\", \"tag2\"].",
            "items": {
              "type": "string"
            },
            "type": "array"
          }
        },
        "type": "object"
      },
      "name": "cx_recall",
      "outputSchema": {
        "description": "Recall response: query header, ranked rows, and trailing advisories.",
        "properties": {
          "advisories": {
            "description": "Trailer advisory lines (routing, tier, dedup, drill-down) the formatter would emit as YAML comments.",
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "entries": {
            "description": "Ranked recall rows. Order is significant.",
            "items": {
              "properties": {
                "age": {
                  "description": "Relative age string (e.g. \"2h\", \"6d\").",
                  "type": "string"
                },
                "id": {
                  "description": "Full UUID v7.",
                  "format": "uuid",
                  "type": "string"
                },
                "kind": {
                  "enum": [
                    "fact",
                    "decision",
                    "preference",
                    "lesson",
                    "reference",
                    "feedback",
                    "pattern",
                    "observation"
                  ],
                  "type": "string"
                },
                "scope": {
                  "type": "string"
                },
                "score": {
                  "description": "Normalised relevance score in [0, 1] on Search routing. Omitted on non-search routings.",
                  "type": "number"
                },
                "snippet": {
                  "description": "Smart snippet of the entry body, with matched query terms bracketed when applicable.",
                  "type": "string"
                },
                "tags": {
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                },
                "title": {
                  "type": "string"
                }
              },
              "required": [
                "id",
                "title",
                "snippet",
                "age",
                "scope",
                "kind",
                "tags"
              ],
              "type": "object"
            },
            "type": "array"
          },
          "header": {
            "description": "Per-response query envelope.",
            "properties": {
              "candidates": {
                "description": "Total candidates considered before token-budget trimming.",
                "minimum": 0,
                "type": "integer"
              },
              "kinds_histogram": {
                "additionalProperties": {
                  "minimum": 0,
                  "type": "integer"
                },
                "description": "Per-kind counts across the returned rows.",
                "type": "object"
              },
              "query": {
                "description": "Free-text query the caller supplied. Omitted when the recall was tag/scope-only.",
                "type": "string"
              },
              "returned": {
                "description": "Number of rows in `entries` after token-budget trimming.",
                "minimum": 0,
                "type": "integer"
              },
              "routing": {
                "description": "Routing branch chosen by the recall pipeline (search, browse_fallback, scope_resolve, tag_scope_walk).",
                "type": "string"
              },
              "scope_chain": {
                "description": "Scope path plus ancestors walked, in order.",
                "items": {
                  "type": "string"
                },
                "type": "array"
              },
              "scope_hits": {
                "additionalProperties": {
                  "minimum": 0,
                  "type": "integer"
                },
                "description": "Per-scope hit counts in `scope_chain`.",
                "type": "object"
              },
              "tags_histogram": {
                "additionalProperties": {
                  "minimum": 0,
                  "type": "integer"
                },
                "description": "Per-tag counts across the returned rows.",
                "type": "object"
              },
              "tier": {
                "description": "Search tier the cascade settled on (none, exact, prefix, split_or). Omitted on non-search routings.",
                "type": "string"
              },
              "tokens": {
                "description": "Estimated token total of the rendered response.",
                "minimum": 0,
                "type": "integer"
              }
            },
            "required": [
              "routing",
              "candidates",
              "returned",
              "scope_chain",
              "scope_hits",
              "kinds_histogram",
              "tags_histogram",
              "tokens"
            ],
            "type": "object"
          }
        },
        "required": [
          "header",
          "entries",
          "advisories"
        ],
        "type": "object"
      }
    },
    {
      "description": "Store a single context entry with structured metadata. Scopes are auto-created if they do not exist. Use 'supersedes' to replace an existing entry (soft-deletes the old one). Returns the new entry ID and content hash.",
      "inputSchema": {
        "properties": {
          "body": {
            "description": "Full content body in markdown.",
            "type": "string"
          },
          "confidence": {
            "description": "Confidence level. Affects recall priority ordering: high entries surface before low entries at the same scope level.",
            "enum": [
              "high",
              "medium",
              "low"
            ],
            "type": "string"
          },
          "created_by": {
            "description": "Attribution string. Format: 'source_type:identifier'. Examples: 'human:stuart', 'agent:claude-code', 'system:consolidation'. Default: 'agent:claude-code'.",
            "type": "string"
          },
          "expires_at": {
            "description": "ISO 8601 expiry timestamp. After this time the entry is considered stale. Stored but not enforced by the storage layer.",
            "type": "string"
          },
          "kind": {
            "description": "Entry classification. Determines recall priority. fact: verified information. decision: architectural choice with rationale. preference: user/project preference. lesson: learned from experience. reference: pointer to external material. feedback: user correction (highest priority). pattern: recurring code/process pattern. observation: general-purpose note.",
            "enum": [
              "fact",
              "decision",
              "preference",
              "lesson",
              "reference",
              "feedback",
              "pattern",
              "observation"
            ],
            "type": "string"
          },
          "priority": {
            "description": "Numeric priority for manual ordering. Higher values surface first in recall results.",
            "type": "integer"
          },
          "scope_path": {
            "description": "Target scope path. Auto-created with ancestor chain if it does not exist. Default: 'global'. Format: 'global', 'global/project:<id>', 'global/project:<id>/repo:<id>', 'global/project:<id>/repo:<id>/session:<id>'.",
            "type": "string"
          },
          "source": {
            "description": "Source URL or file path for reference entries.",
            "type": "string"
          },
          "supersedes": {
            "description": "ID of an existing entry that this new entry replaces. The old entry is soft-deleted and linked via a 'supersedes' relation.",
            "type": "string"
          },
          "tags": {
            "description": "Freeform tags for categorization and filtering. Pass a JSON array: [\"tag1\", \"tag2\"].",
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "title": {
            "description": "Short summary of the entry. Displayed in search results and browse listings.",
            "type": "string"
          }
        },
        "required": [
          "title",
          "body",
          "kind"
        ],
        "type": "object"
      },
      "name": "cx_store"
    },
    {
      "description": "Batch-store conversation exchanges for future context. Each exchange (user/assistant pair) becomes an observation entry. Optional summary creates a linked observation with 'elaborates' relations to each exchange. All entries created in a single transaction. Maximum 50 exchanges per deposit.",
      "inputSchema": {
        "properties": {
          "created_by": {
            "description": "Attribution string. Default: 'agent:claude-code'.",
            "type": "string"
          },
          "exchanges": {
            "description": "Conversation exchanges to store. Each exchange has 'user' (user message), 'assistant' (assistant response), and optional 'title' (explicit title, max 80 bytes; auto-generated from user message snippet if omitted). Maximum 50 exchanges per deposit.",
            "items": {
              "properties": {
                "assistant": {
                  "type": "string"
                },
                "user": {
                  "type": "string"
                }
              },
              "required": [
                "user",
                "assistant"
              ],
              "type": "object"
            },
            "type": "array"
          },
          "scope_path": {
            "description": "Target scope path. Auto-created if missing. Default: 'global'.",
            "type": "string"
          },
          "summary": {
            "description": "Optional summary of the conversation. Stored as a separate observation entry linked to each exchange via 'elaborates' relations.",
            "type": "string"
          }
        },
        "required": [
          "exchanges"
        ],
        "type": "object"
      },
      "name": "cx_deposit"
    },
    {
      "description": "List entries with filtering and cursor-based pagination. For inventory and exploration, not semantic search. Returns metadata + snippet (two-phase retrieval). Filters combine with AND semantics. Results ordered by updated_at DESC.",
      "inputSchema": {
        "properties": {
          "created_by": {
            "description": "Filter by creator attribution string.",
            "type": "string"
          },
          "cursor": {
            "description": "Opaque pagination cursor from a previous cx_browse response. Pass next_cursor to fetch the next page.",
            "type": "string"
          },
          "include_superseded": {
            "description": "Include superseded (inactive) entries in results. Default: false.",
            "type": "boolean"
          },
          "kind": {
            "description": "Filter by entry kind.",
            "enum": [
              "fact",
              "decision",
              "preference",
              "lesson",
              "reference",
              "feedback",
              "pattern",
              "observation"
            ],
            "type": "string"
          },
          "limit": {
            "description": "Maximum entries per page. Default: 20, max: 200.",
            "type": "integer"
          },
          "scope_path": {
            "description": "Filter to entries at this exact scope path (no ancestor walk). Omit to browse across all scopes.",
            "type": "string"
          },
          "tag": {
            "description": "Filter by tag. Entries must have at least one matching tag.",
            "type": "string"
          }
        },
        "type": "object"
      },
      "name": "cx_browse",
      "outputSchema": {
        "description": "Browse response: filtered inventory header, rows, and pagination tail.",
        "properties": {
          "entries": {
            "description": "Browse rows on this page. Order is significant (sort_used governs).",
            "items": {
              "properties": {
                "age": {
                  "description": "Relative age string (e.g. \"2h\", \"6d\").",
                  "type": "string"
                },
                "id": {
                  "description": "Full UUID v7.",
                  "format": "uuid",
                  "type": "string"
                },
                "kind": {
                  "description": "Entry kind. Omitted when unset.",
                  "enum": [
                    "fact",
                    "decision",
                    "preference",
                    "lesson",
                    "reference",
                    "feedback",
                    "pattern",
                    "observation"
                  ],
                  "type": "string"
                },
                "scope": {
                  "description": "Row scope path. Omitted when the row has no scope.",
                  "type": "string"
                },
                "snippet": {
                  "description": "Smart snippet of the entry body.",
                  "type": "string"
                },
                "tags": {
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                },
                "title": {
                  "type": "string"
                }
              },
              "required": [
                "id",
                "title",
                "snippet",
                "age",
                "tags"
              ],
              "type": "object"
            },
            "type": "array"
          },
          "has_more": {
            "description": "True when another page is available via `next_cursor`.",
            "type": "boolean"
          },
          "header": {
            "description": "Per-response filter + histogram envelope.",
            "properties": {
              "created_by": {
                "description": "Created-by filter the caller supplied. Omitted when unset.",
                "type": "string"
              },
              "kind": {
                "description": "Kind filter the caller supplied. Omitted when unset.",
                "type": "string"
              },
              "kinds_histogram": {
                "additionalProperties": {
                  "minimum": 0,
                  "type": "integer"
                },
                "description": "Per-kind counts across the returned rows.",
                "type": "object"
              },
              "returned": {
                "description": "Number of rows in `entries` on this page.",
                "minimum": 0,
                "type": "integer"
              },
              "scope": {
                "description": "Scope filter the caller supplied. Omitted when unset.",
                "type": "string"
              },
              "sort_used": {
                "description": "Sort order the browse pipeline applied (e.g. updated_desc).",
                "type": "string"
              },
              "tags_histogram": {
                "additionalProperties": {
                  "minimum": 0,
                  "type": "integer"
                },
                "description": "Per-tag counts across the returned rows.",
                "type": "object"
              },
              "total": {
                "description": "Total matching rows in the store before pagination.",
                "minimum": 0,
                "type": "integer"
              }
            },
            "required": [
              "sort_used",
              "total",
              "returned",
              "kinds_histogram",
              "tags_histogram"
            ],
            "type": "object"
          },
          "next_cursor": {
            "description": "Opaque cursor to feed back as `cursor` on the next page. Omitted when `has_more` is false.",
            "type": "string"
          }
        },
        "required": [
          "header",
          "entries",
          "has_more"
        ],
        "type": "object"
      }
    },
    {
      "description": "Fetch full content for specific entry IDs. Phase 2 of two-phase retrieval. Use after cx_recall or cx_browse to load full body content. Accepts full hyphenated UUIDv7 strings only. IDs that do not exist are silently omitted. Maximum 100 IDs per request.",
      "inputSchema": {
        "properties": {
          "ids": {
            "description": "Entry IDs: full hyphenated UUIDv7 strings. Max 100 per request.",
            "items": {
              "type": "string"
            },
            "type": "array"
          }
        },
        "required": [
          "ids"
        ],
        "type": "object"
      },
      "name": "cx_get",
      "outputSchema": {
        "description": "Get response: request/found counts, missing ids, and full entries.",
        "properties": {
          "entries": {
            "description": "Resolved entries with full body. Omitted when empty. Order mirrors the caller's request.",
            "items": {
              "properties": {
                "age": {
                  "description": "Relative age string (e.g. \"2h\", \"6d\").",
                  "type": "string"
                },
                "body": {
                  "description": "Full markdown body.",
                  "type": "string"
                },
                "confidence": {
                  "description": "Entry confidence level. Omitted when `meta.confidence` is unset.",
                  "enum": [
                    "high",
                    "medium",
                    "low"
                  ],
                  "type": "string"
                },
                "id": {
                  "description": "Full UUID v7.",
                  "format": "uuid",
                  "type": "string"
                },
                "kind": {
                  "enum": [
                    "fact",
                    "decision",
                    "preference",
                    "lesson",
                    "reference",
                    "feedback",
                    "pattern",
                    "observation"
                  ],
                  "type": "string"
                },
                "scope": {
                  "description": "Canonical scope path.",
                  "type": "string"
                },
                "tags": {
                  "description": "Entry tags. Omitted when `meta.tags` is empty.",
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                },
                "title": {
                  "type": "string"
                }
              },
              "required": [
                "id",
                "title",
                "scope",
                "kind",
                "age",
                "body"
              ],
              "type": "object"
            },
            "type": "array"
          },
          "found": {
            "description": "Number of entries successfully resolved from the store.",
            "minimum": 0,
            "type": "integer"
          },
          "missing": {
            "description": "Ids the caller supplied that did not resolve. Omitted when empty.",
            "items": {
              "description": "Verbatim id the caller passed; not guaranteed to be a valid UUID.",
              "type": "string"
            },
            "type": "array"
          },
          "requested": {
            "description": "Number of ids the caller supplied.",
            "minimum": 0,
            "type": "integer"
          }
        },
        "required": [
          "requested",
          "found"
        ],
        "type": "object"
      }
    },
    {
      "description": "Partially update an existing entry. Only provided fields are modified. Changing body or kind recomputes content_hash and checks for duplicates. Scope migration is excluded; use cx_store with supersedes to move entries across scopes. At least one field must be provided.",
      "inputSchema": {
        "properties": {
          "body": {
            "description": "New body content in markdown. Changing body recomputes content_hash and checks for duplicates. Omit to keep existing.",
            "type": "string"
          },
          "id": {
            "description": "ID of the entry to update.",
            "type": "string"
          },
          "kind": {
            "description": "New kind classification. Changing kind recomputes content_hash. Omit to keep existing.",
            "enum": [
              "fact",
              "decision",
              "preference",
              "lesson",
              "reference",
              "feedback",
              "pattern",
              "observation"
            ],
            "type": "string"
          },
          "meta": {
            "description": "Replace metadata entirely. Provide the complete desired meta object with fields: tags (array), confidence (high/medium/low), source (string), expires_at (ISO 8601), priority (integer). Omit to keep existing metadata.",
            "type": "object"
          },
          "title": {
            "description": "New title. Omit to keep existing.",
            "type": "string"
          }
        },
        "required": [
          "id"
        ],
        "type": "object"
      },
      "name": "cx_update"
    },
    {
      "description": "Soft-delete entries by marking them as forgotten. Sets superseded_by to the entry's own ID, distinguishing forgotten entries from entries superseded by a replacement. Already-inactive entries are silently skipped. Maximum 100 IDs per request. Partial success is reported.",
      "inputSchema": {
        "properties": {
          "ids": {
            "description": "Entry IDs to forget. Maximum 100 per request. Each ID is processed independently.",
            "items": {
              "type": "string"
            },
            "type": "array"
          }
        },
        "required": [
          "ids"
        ],
        "type": "object"
      },
      "name": "cx_forget"
    },
    {
      "description": "View aggregate statistics about the context store. Returns active/superseded entry counts, scope count, relation count, breakdown by kind, by scope, and by tag, database file size, and scope tree. Diagnostic tool for understanding what context exists.",
      "inputSchema": {
        "properties": {
          "tag_sort": {
            "description": "Sort order for tag breakdown. 'name': alphabetical ascending (default). 'count': most used tags first.",
            "enum": [
              "name",
              "count"
            ],
            "type": "string"
          }
        },
        "type": "object"
      },
      "name": "cx_stats",
      "outputSchema": {
        "description": "Stats response: store totals, per-kind histogram, top tags, and scope tree.",
        "properties": {
          "active": {
            "description": "Number of active (non-superseded) entries.",
            "minimum": 0,
            "type": "integer"
          },
          "db_size_bytes": {
            "description": "SQLite database file size in bytes.",
            "minimum": 0,
            "type": "integer"
          },
          "kinds": {
            "additionalProperties": {
              "minimum": 0,
              "type": "integer"
            },
            "description": "Per-kind entry counts across active entries.",
            "type": "object"
          },
          "relations": {
            "description": "Total relations in the store.",
            "minimum": 0,
            "type": "integer"
          },
          "scope_tree": {
            "description": "Scope tree rows in traversal order.",
            "items": {
              "properties": {
                "entry_count": {
                  "description": "Active entries at this scope (non-recursive).",
                  "minimum": 0,
                  "type": "integer"
                },
                "kind": {
                  "description": "ScopeKind serialised as a string (global, project, repo, session).",
                  "type": "string"
                },
                "label": {
                  "description": "Human-readable label for the scope.",
                  "type": "string"
                },
                "path": {
                  "description": "Canonical scope path.",
                  "type": "string"
                }
              },
              "required": [
                "path",
                "kind",
                "label",
                "entry_count"
              ],
              "type": "object"
            },
            "type": "array"
          },
          "scopes": {
            "description": "Total scopes in the store.",
            "minimum": 0,
            "type": "integer"
          },
          "superseded": {
            "description": "Number of superseded (soft-deleted or replaced) entries.",
            "minimum": 0,
            "type": "integer"
          },
          "top_tags": {
            "description": "Most frequent tags, capped at 10 by `TOP_TAGS_LIMIT`.",
            "items": {
              "properties": {
                "count": {
                  "minimum": 0,
                  "type": "integer"
                },
                "tag": {
                  "type": "string"
                }
              },
              "required": [
                "tag",
                "count"
              ],
              "type": "object"
            },
            "type": "array"
          }
        },
        "required": [
          "active",
          "superseded",
          "scopes",
          "relations",
          "db_size_bytes",
          "kinds",
          "top_tags",
          "scope_tree"
        ],
        "type": "object"
      }
    },
    {
      "description": "Export entries and scopes as JSON for backup or migration. Returns all active entries (superseded excluded) and their scopes. Relations are excluded in v1. Optionally filter to a specific scope subtree.",
      "inputSchema": {
        "properties": {
          "format": {
            "description": "Export format. Currently only 'json' is supported. Default: 'json'.",
            "enum": [
              "json"
            ],
            "type": "string"
          },
          "scope_path": {
            "description": "Filter export to a specific scope path and its descendants. Omit to export everything.",
            "type": "string"
          }
        },
        "type": "object"
      },
      "name": "cx_export",
      "outputSchema": {
        "description": "Export response: full entry and scope snapshots plus provenance metadata.",
        "properties": {
          "count": {
            "description": "Length of `entries`.",
            "minimum": 0,
            "type": "integer"
          },
          "entries": {
            "description": "Active entries in the export scope. Mirrors `cm_core::Entry`.",
            "items": {
              "properties": {
                "body": {
                  "description": "Full markdown body.",
                  "type": "string"
                },
                "content_hash": {
                  "description": "BLAKE3 hex digest of the body.",
                  "type": "string"
                },
                "created_at": {
                  "format": "date-time",
                  "type": "string"
                },
                "created_by": {
                  "description": "Attribution string (e.g. agent:claude-code).",
                  "type": "string"
                },
                "id": {
                  "format": "uuid",
                  "type": "string"
                },
                "kind": {
                  "enum": [
                    "fact",
                    "decision",
                    "preference",
                    "lesson",
                    "reference",
                    "feedback",
                    "pattern",
                    "observation"
                  ],
                  "type": "string"
                },
                "meta": {
                  "additionalProperties": true,
                  "description": "Optional metadata envelope. Omitted when every sub-field is empty.",
                  "properties": {
                    "confidence": {
                      "enum": [
                        "high",
                        "medium",
                        "low"
                      ],
                      "type": "string"
                    },
                    "expires_at": {
                      "format": "date-time",
                      "type": "string"
                    },
                    "priority": {
                      "type": "integer"
                    },
                    "source": {
                      "type": "string"
                    },
                    "tags": {
                      "items": {
                        "type": "string"
                      },
                      "type": "array"
                    }
                  },
                  "type": "object"
                },
                "scope_path": {
                  "description": "Canonical scope path.",
                  "type": "string"
                },
                "superseded_by": {
                  "description": "Id of the replacement entry when this row is soft-deleted.",
                  "format": "uuid",
                  "type": "string"
                },
                "title": {
                  "type": "string"
                },
                "updated_at": {
                  "format": "date-time",
                  "type": "string"
                }
              },
              "required": [
                "id",
                "scope_path",
                "kind",
                "title",
                "body",
                "content_hash",
                "created_by",
                "created_at",
                "updated_at"
              ],
              "type": "object"
            },
            "type": "array"
          },
          "exported_at": {
            "description": "Export timestamp in RFC 3339.",
            "format": "date-time",
            "type": "string"
          },
          "scopes": {
            "description": "Scopes touched by the export. Mirrors `cm_core::Scope`.",
            "items": {
              "properties": {
                "created_at": {
                  "format": "date-time",
                  "type": "string"
                },
                "kind": {
                  "description": "ScopeKind serialised as a string.",
                  "type": "string"
                },
                "label": {
                  "type": "string"
                },
                "meta": {
                  "additionalProperties": true,
                  "description": "Free-form scope metadata. Omitted when unset.",
                  "type": "object"
                },
                "parent_path": {
                  "description": "Parent scope path. Omitted for the root scope.",
                  "type": "string"
                },
                "path": {
                  "type": "string"
                }
              },
              "required": [
                "path",
                "kind",
                "label",
                "created_at"
              ],
              "type": "object"
            },
            "type": "array"
          }
        },
        "required": [
          "entries",
          "scopes",
          "exported_at",
          "count"
        ],
        "type": "object"
      }
    }
  ]
}"##).expect("generated tool list is valid JSON")
}
