// AUTO-GENERATED by build.rs from tools.toml - do not edit
#![allow(clippy::all)]

pub fn generated_tool_list() -> serde_json::Value {
    let tools: Vec<serde_json::Value> = vec![
        serde_json::from_str(include_str!("generated_schema/cx_recall.json"))
            .expect("generated schema for cx_recall is valid JSON"),
        serde_json::from_str(include_str!("generated_schema/cx_store.json"))
            .expect("generated schema for cx_store is valid JSON"),
        serde_json::from_str(include_str!("generated_schema/cx_deposit.json"))
            .expect("generated schema for cx_deposit is valid JSON"),
        serde_json::from_str(include_str!("generated_schema/cx_browse.json"))
            .expect("generated schema for cx_browse is valid JSON"),
        serde_json::from_str(include_str!("generated_schema/cx_get.json"))
            .expect("generated schema for cx_get is valid JSON"),
        serde_json::from_str(include_str!("generated_schema/cx_update.json"))
            .expect("generated schema for cx_update is valid JSON"),
        serde_json::from_str(include_str!("generated_schema/cx_forget.json"))
            .expect("generated schema for cx_forget is valid JSON"),
        serde_json::from_str(include_str!("generated_schema/cx_stats.json"))
            .expect("generated schema for cx_stats is valid JSON"),
        serde_json::from_str(include_str!("generated_schema/cx_export.json"))
            .expect("generated schema for cx_export is valid JSON"),
    ];
    serde_json::json!({ "tools": tools })
}
