// AUTO-GENERATED by build.rs from tools.toml — do not edit
#![allow(clippy::all)]
#[rustfmt::skip]

pub fn generated_tool_list() -> serde_json::Value {
serde_json::from_str(r##"{
  "tools": [
    {
      "description": "Search and retrieve context entries relevant to the current task. Primary retrieval tool. Combines FTS5 keyword search with scope resolution (ancestor walk). Call after receiving a task with a summary of what you are working on. When query is omitted, returns all entries at the target scope via ancestor walk. Returns metadata + snippet for two-phase retrieval; use cx_get for full body. IMPORTANT: The query uses FTS5 with implicit AND between words. Use 1-3 keywords, not full sentences. More words = fewer results. Examples: 'auth migration' (good), 'how does the authentication migration work' (too many words, likely 0 results). Use OR for alternatives: 'auth OR authentication'. Use prefix matching: 'migrat*'.",
      "inputSchema": {
        "properties": {
          "kinds": {
            "description": "Filter to specific entry kinds (OR logic). Valid values: fact, decision, preference, lesson, reference, feedback, pattern, observation.",
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "limit": {
            "description": "Maximum number of entries to return. Default: 20, max: 200.",
            "type": "integer"
          },
          "max_tokens": {
            "description": "Maximum token budget for the response. Results are trimmed to fit within this budget, prioritizing higher-relevance entries. Uses ~4 chars/token estimation.",
            "type": "integer"
          },
          "query": {
            "description": "FTS5 search query. Use 1-3 keywords (implicit AND). Do NOT pass full sentences. Supports prefix queries (rust*), phrase queries (\"scope path\"), and boolean operators (AND, OR, NOT). Use OR between synonyms: 'auth OR authentication'. Omit to return all entries at the target scope via ancestor walk.",
            "type": "string"
          },
          "scope": {
            "description": "Scope path to search within. Retrieves entries from this scope and all ancestor scopes. Example: 'global/project:helioy/repo:nancyr' also searches 'global/project:helioy' and 'global'. Default: 'global'.",
            "type": "string"
          },
          "tags": {
            "description": "Filter to entries with any of these tags (OR logic).",
            "items": {
              "type": "string"
            },
            "type": "array"
          }
        },
        "type": "object"
      },
      "name": "cx_recall"
    },
    {
      "description": "Store a single context entry with structured metadata. Scopes are auto-created if they do not exist. Use 'supersedes' to replace an existing entry (soft-deletes the old one). Returns the new entry ID and content hash.",
      "inputSchema": {
        "properties": {
          "body": {
            "description": "Full content body in markdown.",
            "type": "string"
          },
          "confidence": {
            "description": "Confidence level. Affects recall priority ordering: high entries surface before low entries at the same scope level.",
            "enum": [
              "high",
              "medium",
              "low"
            ],
            "type": "string"
          },
          "created_by": {
            "description": "Attribution string. Format: 'source_type:identifier'. Examples: 'human:stuart', 'agent:claude-code', 'system:consolidation'. Default: 'agent:claude-code'.",
            "type": "string"
          },
          "expires_at": {
            "description": "ISO 8601 expiry timestamp. After this time the entry is considered stale. Stored but not enforced by the storage layer.",
            "type": "string"
          },
          "kind": {
            "description": "Entry classification. Determines recall priority. fact: verified information. decision: architectural choice with rationale. preference: user/project preference. lesson: learned from experience. reference: pointer to external material. feedback: user correction (highest priority). pattern: recurring code/process pattern. observation: general-purpose note.",
            "enum": [
              "fact",
              "decision",
              "preference",
              "lesson",
              "reference",
              "feedback",
              "pattern",
              "observation"
            ],
            "type": "string"
          },
          "priority": {
            "description": "Numeric priority for manual ordering. Higher values surface first in recall results.",
            "type": "integer"
          },
          "scope_path": {
            "description": "Target scope path. Auto-created with ancestor chain if it does not exist. Default: 'global'. Format: 'global', 'global/project:<id>', 'global/project:<id>/repo:<id>', 'global/project:<id>/repo:<id>/session:<id>'.",
            "type": "string"
          },
          "source": {
            "description": "Source URL or file path for reference entries.",
            "type": "string"
          },
          "supersedes": {
            "description": "ID of an existing entry that this new entry replaces. The old entry is soft-deleted and linked via a 'supersedes' relation.",
            "type": "string"
          },
          "tags": {
            "description": "Freeform tags for categorization and filtering.",
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "title": {
            "description": "Short summary of the entry. Displayed in search results and browse listings.",
            "type": "string"
          }
        },
        "required": [
          "title",
          "body",
          "kind"
        ],
        "type": "object"
      },
      "name": "cx_store"
    },
    {
      "description": "Batch-store conversation exchanges for future context. Each exchange (user/assistant pair) becomes an observation entry. Optional summary creates a linked observation with 'elaborates' relations to each exchange. All entries created in a single transaction. Maximum 50 exchanges per deposit.",
      "inputSchema": {
        "properties": {
          "created_by": {
            "description": "Attribution string. Default: 'agent:claude-code'.",
            "type": "string"
          },
          "exchanges": {
            "description": "Conversation exchanges to store. Each exchange has 'user' (user message), 'assistant' (assistant response), and optional 'title' (explicit title, max 80 bytes; auto-generated from user message snippet if omitted). Maximum 50 exchanges per deposit.",
            "items": {
              "properties": {
                "assistant": {
                  "type": "string"
                },
                "user": {
                  "type": "string"
                }
              },
              "required": [
                "user",
                "assistant"
              ],
              "type": "object"
            },
            "type": "array"
          },
          "scope_path": {
            "description": "Target scope path. Auto-created if missing. Default: 'global'.",
            "type": "string"
          },
          "summary": {
            "description": "Optional summary of the conversation. Stored as a separate observation entry linked to each exchange via 'elaborates' relations.",
            "type": "string"
          }
        },
        "required": [
          "exchanges"
        ],
        "type": "object"
      },
      "name": "cx_deposit"
    },
    {
      "description": "List entries with filtering and cursor-based pagination. For inventory and exploration, not semantic search. Returns metadata + snippet (two-phase retrieval). Filters combine with AND semantics. Results ordered by updated_at DESC.",
      "inputSchema": {
        "properties": {
          "created_by": {
            "description": "Filter by creator attribution string.",
            "type": "string"
          },
          "cursor": {
            "description": "Opaque pagination cursor from a previous cx_browse response. Pass next_cursor to fetch the next page.",
            "type": "string"
          },
          "include_superseded": {
            "description": "Include superseded (inactive) entries in results. Default: false.",
            "type": "boolean"
          },
          "kind": {
            "description": "Filter by entry kind.",
            "enum": [
              "fact",
              "decision",
              "preference",
              "lesson",
              "reference",
              "feedback",
              "pattern",
              "observation"
            ],
            "type": "string"
          },
          "limit": {
            "description": "Maximum entries per page. Default: 20, max: 200.",
            "type": "integer"
          },
          "scope_path": {
            "description": "Filter to entries at this exact scope path (no ancestor walk). Omit to browse across all scopes.",
            "type": "string"
          },
          "tag": {
            "description": "Filter by tag. Entries must have at least one matching tag.",
            "type": "string"
          }
        },
        "type": "object"
      },
      "name": "cx_browse"
    },
    {
      "description": "Fetch full content for specific entry IDs. Phase 2 of two-phase retrieval. Use after cx_recall or cx_browse to load full body content. IDs that do not exist are silently omitted. Maximum 100 IDs per request.",
      "inputSchema": {
        "properties": {
          "ids": {
            "description": "Entry IDs to retrieve (UUIDv7 format). Maximum 100 per request. Missing IDs are silently omitted.",
            "items": {
              "type": "string"
            },
            "type": "array"
          }
        },
        "required": [
          "ids"
        ],
        "type": "object"
      },
      "name": "cx_get"
    },
    {
      "description": "Partially update an existing entry. Only provided fields are modified. Changing body or kind recomputes content_hash and checks for duplicates. Scope migration is excluded; use cx_store with supersedes to move entries across scopes. At least one field must be provided.",
      "inputSchema": {
        "properties": {
          "body": {
            "description": "New body content in markdown. Changing body recomputes content_hash and checks for duplicates. Omit to keep existing.",
            "type": "string"
          },
          "id": {
            "description": "ID of the entry to update.",
            "type": "string"
          },
          "kind": {
            "description": "New kind classification. Changing kind recomputes content_hash. Omit to keep existing.",
            "enum": [
              "fact",
              "decision",
              "preference",
              "lesson",
              "reference",
              "feedback",
              "pattern",
              "observation"
            ],
            "type": "string"
          },
          "meta": {
            "description": "Replace metadata entirely. Provide the complete desired meta object with fields: tags (array), confidence (high/medium/low), source (string), expires_at (ISO 8601), priority (integer). Omit to keep existing metadata.",
            "type": "object"
          },
          "title": {
            "description": "New title. Omit to keep existing.",
            "type": "string"
          }
        },
        "required": [
          "id"
        ],
        "type": "object"
      },
      "name": "cx_update"
    },
    {
      "description": "Soft-delete entries by marking them as forgotten. Sets superseded_by to the entry's own ID, distinguishing forgotten entries from entries superseded by a replacement. Already-inactive entries are silently skipped. Maximum 100 IDs per request. Partial success is reported.",
      "inputSchema": {
        "properties": {
          "ids": {
            "description": "Entry IDs to forget. Maximum 100 per request. Each ID is processed independently.",
            "items": {
              "type": "string"
            },
            "type": "array"
          }
        },
        "required": [
          "ids"
        ],
        "type": "object"
      },
      "name": "cx_forget"
    },
    {
      "description": "View aggregate statistics about the context store. Returns active/superseded entry counts, scope count, relation count, breakdown by kind, by scope, and by tag, database file size, and scope tree. Diagnostic tool for understanding what context exists.",
      "inputSchema": {
        "properties": {
          "tag_sort": {
            "description": "Sort order for tag breakdown. 'name': alphabetical ascending (default). 'count': most used tags first.",
            "enum": [
              "name",
              "count"
            ],
            "type": "string"
          }
        },
        "type": "object"
      },
      "name": "cx_stats"
    },
    {
      "description": "Export entries and scopes as JSON for backup or migration. Returns all active entries (superseded excluded) and their scopes. Relations are excluded in v1. Optionally filter to a specific scope subtree.",
      "inputSchema": {
        "properties": {
          "format": {
            "description": "Export format. Currently only 'json' is supported. Default: 'json'.",
            "enum": [
              "json"
            ],
            "type": "string"
          },
          "scope_path": {
            "description": "Filter export to a specific scope path and its descendants. Omit to export everything.",
            "type": "string"
          }
        },
        "type": "object"
      },
      "name": "cx_export"
    }
  ]
}"##).expect("generated tool list is valid JSON")
}
