//! Generated documentation renderers for the cx tool contract registry.

use crate::tool_contracts::{
    ArrayItems, ParamShape, ScopeFragment, ScopeInputShape, SkillConfig, ToolContract,
    ToolParamContract,
};
use std::fmt::Write;

const README_PREAMBLE: &str = r#"<!-- AUTO-GENERATED by crates/cm-cli/build.rs from tools.toml. Do not edit generated tool and scope sections by hand. -->

# context-matters

Structured context store for AI agents. SQLite-backed, scoped, searchable.

Agents accumulate knowledge during sessions: decisions made, feedback received, patterns discovered, lessons learned. Without persistence, every session starts from zero. context-matters gives agents a place to store and retrieve that knowledge across sessions, projects, and scopes.

## Install

```bash
npx context-matters serve    # MCP server on stdio
```

Or build from source:

```bash
cargo install --path crates/cm-cli
```

## MCP server

Runs as a Model Context Protocol server. Ten tools, all prefixed `cx_*`.

```bash
cm serve
```

This CLI mirrors the MCP tool surface. From a shell, use `cm <command>`.
From an MCP client, the same operations are exposed as `cx_<command>`.
Run `cm serve` to start the MCP server on stdio.

"#;

const README_FOOTER: &str = r#"## Web UI

Run `cm web --open` for browser entry management and monitoring. It serves `http://localhost:3141/` by default.

## Architecture

Five crates, clean separation:

| Crate | What it does |
|-------|-------------|
| `cm-core` | Domain types, ContextStore trait, query construction. Zero I/O. |
| `cm-store` | SQLite adapter via sqlx. WAL mode, FTS5 search, BLAKE3 dedup. |
| `cm-capabilities` | Shared request/response types, validation, scope resolution, projections. |
| `cm-cli` | CLI binary + MCP server. Tool docs generated from `tools.toml`. |
| `cm-web` | Web monitoring dashboard with Axum and React/Vite. Run `cm web --open`; default URL: `http://localhost:3141/`. |

## Development

Rust 2024 edition. [just](https://github.com/casey/just) as task runner.

```bash
just check    # fmt + clippy (warnings = errors)
just build    # cargo build --workspace
just test     # cargo test --workspace
just fmt      # rustfmt
```

## License

MIT
"#;

pub fn render_skill_md(skill: Option<&SkillConfig>, tools: &[ToolContract]) -> String {
    let mut out = String::new();
    append_skill_frontmatter(&mut out);
    append_skill_intro(&mut out);
    append_tool_summary_table(&mut out, tools, true);

    if let Some(skill) = skill {
        out.push_str(skill.workflow.trim_start_matches('\n'));
        out.push('\n');
    }

    append_scope_model(&mut out, tools, 3);
    append_two_phase_retrieval(&mut out, tools, 3);
    append_parameter_reference(&mut out, tools);
    append_skill_rules(&mut out, tools);
    append_cli_fallback(&mut out);
    out
}

pub fn render_server_instructions(tools: &[ToolContract]) -> String {
    let mut out = String::new();
    out.push_str(
        "You have a structured context store for persistent project knowledge across sessions.\n\n",
    );
    out.push_str("TASK WORKFLOW:\n");
    out.push_str("1. RECALL: After receiving a task with a known scope, call cx_recall with a summary of what you are working on. This returns priority context from the current scope and all ancestor scopes. Use cx_search when the right scope is unknown, broad, or cross-repo. Use returned context silently. cx_recall and cx_search are useful at any point during a session, not only after the initial task.\n");
    out.push_str("2. STORE: When you discover important facts, decisions, user preferences, lessons learned, or recurring patterns, call cx_store to persist them. Classify entries by kind for effective retrieval later.\n");
    out.push_str("3. FEEDBACK: When the user corrects you or clarifies a preference, store it as kind='feedback'. Feedback entries receive highest recall priority.\n\n");

    out.push_str("TOOLS OVERVIEW:\n");
    append_tool_bullets(&mut out, tools);
    out.push('\n');

    out.push_str("SCOPE MODEL:\n");
    append_scope_instruction_lines(&mut out, tools);
    out.push('\n');

    out.push_str("PRINCIPLES:\n");
    append_principle_bullets(&mut out, tools);
    out.trim_end().to_string()
}

pub fn render_generated_instructions_rs(instructions: &str) -> String {
    format!(
        "// AUTO-GENERATED by build.rs from tools.toml - do not edit\n#![allow(clippy::all)]\n\npub const SERVER_INSTRUCTIONS: &str = {instructions:?};\n"
    )
}

pub fn render_readme_md(tools: &[ToolContract]) -> String {
    let mut out = String::new();
    out.push_str(README_PREAMBLE);
    append_tool_summary_table(&mut out, tools, false);
    append_tool_examples(&mut out, tools);
    append_cli_scope_table(&mut out, tools);
    append_cli_examples(&mut out);
    append_scope_model(&mut out, tools, 2);
    append_two_phase_retrieval(&mut out, tools, 2);
    out.push_str(README_FOOTER);
    out
}

fn append_skill_frontmatter(out: &mut String) {
    out.push_str("---\n");
    out.push_str("name: cm\n");
    out.push_str("description: >\n");
    out.push_str("  Structured context store for AI agents. Use before any session to recall\n");
    out.push_str(
        "  relevant knowledge, and during work to persist facts, decisions, preferences,\n",
    );
    out.push_str(
        "  and lessons. All tools are prefixed `cx_*`. Trigger when: starting a session,\n",
    );
    out.push_str(
        "  discovering reusable knowledge, receiving user corrections, or ending a session\n",
    );
    out.push_str("  with conversation deposits.\n");
    out.push_str("---\n\n");
}

fn append_skill_intro(out: &mut String) {
    out.push_str("# Context Matters: Structured Context Store\n\n");
    out.push_str(
        "This project has a structured context store available via the **`cm` MCP server**. ",
    );
    out.push_str(
        "All tools are prefixed `cx_*`. Use them to persist and retrieve project knowledge ",
    );
    out.push_str("across sessions.\n\n");
}

fn append_tool_summary_table(out: &mut String, tools: &[ToolContract], include_examples: bool) {
    out.push_str("## MCP Tools\n\n");
    if include_examples {
        out.push_str("| Tool | Purpose | Example |\n");
        out.push_str("|------|---------|---------|\n");
    } else {
        out.push_str("| Tool | Purpose |\n");
        out.push_str("|------|---------|\n");
    }

    for tool in tools {
        if include_examples {
            let example = tool
                .examples
                .first()
                .map(|example| format!("`{}`", example.invocation))
                .unwrap_or_default();
            let _ = writeln!(
                out,
                "| `{}` | {} | {} |",
                tool.name, tool.descriptions.short, example
            );
        } else {
            let _ = writeln!(out, "| `{}` | {} |", tool.name, tool.descriptions.short);
        }
    }
    out.push('\n');
}

fn append_tool_examples(out: &mut String, tools: &[ToolContract]) {
    out.push_str("## MCP Examples\n\n");
    out.push_str("```text\n");
    for tool in tools {
        for example in &tool.examples {
            out.push_str(&example.invocation);
            out.push('\n');
        }
    }
    out.push_str("```\n\n");
}

fn append_cli_scope_table(out: &mut String, tools: &[ToolContract]) {
    out.push_str("## CLI Commands\n\n");
    out.push_str("The CLI reads from the same store as the `cx_*` MCP tools.\n\n");
    out.push_str("| Command | Purpose | Scope input |\n");
    out.push_str("|---------|---------|-------------|\n");
    for tool in tools {
        let _ = writeln!(
            out,
            "| `cm {}` | {} | {} |",
            tool.cli.name,
            tool.descriptions.short,
            scope_input_label(tool)
        );
    }
    out.push('\n');
}

fn append_cli_examples(out: &mut String) {
    out.push_str("## CLI Examples\n\n");
    out.push_str("```bash\n");
    out.push_str("cm serve\n");
    out.push_str("cm init\n");
    out.push_str("cm init --global\n");
    out.push_str("cm web --open\n");
    out.push_str("cm forget 019d09ed-7a4f-7693\n");
    out.push_str("cm recall \"auth migration\"\n");
    out.push_str("cm search \"auth migration\" --scope '{\"kind\":\"all\"}'\n");
    out.push_str("cm browse --kind decision -j\n");
    out.push_str("cm get 019d09ed-7a4f-7693\n");
    out.push_str("cm stats\n");
    out.push_str(
        "cm export --scope '{\"kind\":\"descendants\",\"path\":\"global/project:helioy\"}'\n",
    );
    out.push_str("```\n\n");
}

fn append_scope_model(out: &mut String, tools: &[ToolContract], heading_level: usize) {
    append_heading(out, heading_level, "Scope Model");
    out.push_str(
        "Scopes form a hierarchy. Context at broader scopes is visible at narrower scopes.\n\n",
    );
    out.push_str("```text\n");
    out.push_str("global                                           cross-project knowledge\n");
    out.push_str("global/project:helioy                           project-level decisions\n");
    out.push_str("global/project:helioy/repo:context-matters      codebase-specific facts\n");
    out.push_str("global/project:helioy/repo:context-matters/session:abc   task context\n");
    out.push_str("```\n\n");
    out.push_str("Public requests select scope through the `scope` field. The canonical scope path string returned by read tools can be passed directly to write tools.\n\n");
    append_scope_fragment_table(out, "Singular Selectors", ScopeInputShape::Singular, true);
    append_scope_fragment_table(out, "Broad Selectors", ScopeInputShape::Broad, false);
    append_scope_boundary_table(out, tools);
    out.push_str("For cwd based browse resolution, call `cx_browse(scope: {\"kind\":\"cwd_inferred\",\"cwd\":\"/path/to/repo\"})`.\n");
    out.push_str("`cwd_inferred` resolves linked git worktrees to the source repository identity. Persisted entries and export rows include `scope_path`. Read projections use `scope` for compact row output.\n\n");
}

fn append_scope_fragment_table(
    out: &mut String,
    title: &str,
    shape: ScopeInputShape,
    include_all: bool,
) {
    let fragments = shape
        .fragments()
        .iter()
        .copied()
        .filter(|fragment| include_all || is_broad_only(*fragment));
    out.push_str(&format!("### {title}\n\n"));
    out.push_str("| Selector | Request example |\n");
    out.push_str("|----------|-----------------|\n");
    for fragment in fragments {
        let _ = writeln!(
            out,
            "| {} | `{}` |",
            scope_fragment_label(fragment),
            fragment.request_example()
        );
    }
    out.push('\n');
}

fn append_scope_boundary_table(out: &mut String, tools: &[ToolContract]) {
    out.push_str("### Tool Scope Boundaries\n\n");
    out.push_str("| Tool | Scope request |\n");
    out.push_str("|------|---------------|\n");
    for tool in tools.iter().filter(|tool| tool.param("scope").is_some()) {
        let _ = writeln!(out, "| `{}` | {} |", tool.name, scope_input_label(tool));
    }
    out.push('\n');
}

fn append_two_phase_retrieval(out: &mut String, tools: &[ToolContract], heading_level: usize) {
    let snippet_tools = tools_with_names(tools, &["cx_recall", "cx_search", "cx_browse"]);
    let get_tool = tools
        .iter()
        .find(|tool| tool.name == "cx_get")
        .map(|tool| tool.name.as_str())
        .unwrap_or("cx_get");

    append_heading(out, heading_level, "Two-Phase Retrieval");
    let _ = writeln!(
        out,
        "{} return metadata plus snippets. Use `{get_tool}` with returned IDs to fetch full body content.",
        inline_tool_list(&snippet_tools)
    );
    out.push_str("This keeps initial responses compact while allowing selective deep reads.\n\n");
}

fn append_parameter_reference(out: &mut String, tools: &[ToolContract]) {
    out.push_str("\n## Parameter Reference\n\n");
    out.push_str("> Auto-generated from tools.toml.\n\n");

    for tool in tools {
        let _ = writeln!(out, "### `{}`\n", tool.name);
        let _ = writeln!(out, "{}\n", tool.descriptions.mcp);

        if !tool.params.is_empty() {
            out.push_str("| Parameter | Type | Required | Description |\n");
            out.push_str("|-----------|------|----------|-------------|\n");
            for param in &tool.params {
                append_parameter_row(out, param);
            }
            out.push('\n');
        }
    }
}

fn append_parameter_row(out: &mut String, param: &ToolParamContract) {
    let req = if param.required { "yes" } else { "no" };
    let type_str = param_type_label(param);
    let desc = if param.mcp_description.len() > 120 {
        format!("{}...", &param.mcp_description[..117])
    } else {
        param.mcp_description.clone()
    };
    let _ = writeln!(
        out,
        "| `{}` | {} | {} | {} |",
        param.name, type_str, req, desc
    );
}

fn append_skill_rules(out: &mut String, tools: &[ToolContract]) {
    out.push_str("## Rules\n\n");
    out.push_str("1. **Call `cx_recall` after receiving a task** with a summary of what you are working on\n");
    out.push_str("2. **Store selectively**. Persist genuinely reusable knowledge, not routine observations\n");
    out.push_str(
        "3. **Classify accurately**. The `kind` field drives recall priority and filtering\n",
    );
    let _ = writeln!(
        out,
        "4. **Use specific `scope` selectors**. Broad selectors are reserved for {}",
        inline_tool_list(&broad_scope_tool_names(tools))
    );
    out.push_str("5. **Two-phase retrieval**. Use `cx_get` when a snippet is not enough\n");
    out.push_str("6. **Store feedback immediately**. When the user corrects you, `kind: \"feedback\"` gets highest recall priority\n");
    out.push_str("7. **Do not mention the context system** to the user unless asked\n");
}

fn append_cli_fallback(out: &mut String) {
    out.push_str("\n## CLI Fallback\n\n");
    out.push_str("If MCP tools are unavailable, use the CLI directly:\n\n");
    out.push_str("```bash\n");
    out.push_str("cm stats     # Show store statistics\n");
    out.push_str("cm serve     # Start MCP server on stdio\n");
    out.push_str("```\n");
}

fn append_tool_bullets(out: &mut String, tools: &[ToolContract]) {
    for tool in tools {
        let _ = writeln!(out, "- {}: {}.", tool.name, tool.descriptions.short);
    }
}

fn append_scope_instruction_lines(out: &mut String, tools: &[ToolContract]) {
    let singular = singular_scope_tool_names(tools);
    let broad = broad_scope_tool_names(tools);
    out.push_str("Scopes form a hierarchy: global > project > repo > session. Context at broader scopes is visible at narrower scopes.\n");
    out.push_str("When storing entries, use the narrowest appropriate scope. Global scope is for cross-project knowledge, project scope is for project-level decisions, repo scope is for codebase-specific facts, and session scope is for ephemeral task context.\n");
    out.push_str(
        "Canonical scope paths returned by read tools can be passed directly to write tools.\n",
    );
    let _ = writeln!(
        out,
        "Singular scope tools are {}. Broad scope tools are {}.",
        inline_tool_list(&singular),
        inline_tool_list(&broad)
    );
    out.push_str("Structured singular selectors include path, cwd_inferred, project, repo, and session. Broad selectors add descendants, subtree, set, and all.\n");
    out.push_str("Example scoped write: cx_store(scope='global/project:helioy/repo:context-matters', title='...', body='...', kind='decision').\n");
    out.push_str("Example scoped deposit: cx_deposit(scope='global/project:helioy/repo:context-matters', exchanges=[...]).\n");
}

fn append_principle_bullets(out: &mut String, tools: &[ToolContract]) {
    let _ = writeln!(
        out,
        "- Use cx_recall for one known scope. Use cx_search when the right scope is unknown, broad, or cross-repo."
    );
    out.push_str("- Be selective. Store genuinely reusable knowledge, not routine observations.\n");
    out.push_str("- Classify accurately. The kind field drives recall priority and filtering.\n");
    let _ = writeln!(
        out,
        "- Use broad selectors only with {}.",
        inline_tool_list(&broad_scope_tool_names(tools))
    );
    out.push_str("- Do not mention the context system to the user unless asked.\n");
    out.push_str("- If cx_recall returns empty results, that is fine. The scope is new.\n");
}

fn append_heading(out: &mut String, level: usize, title: &str) {
    out.push_str(&"#".repeat(level));
    out.push(' ');
    out.push_str(title);
    out.push_str("\n\n");
}

fn scope_input_label(tool: &ToolContract) -> String {
    let Some(param) = tool.param("scope") else {
        return "No scope request parameter".to_string();
    };
    let requirement = if param.required {
        "Required"
    } else {
        "Optional"
    };
    match param.shape {
        ParamShape::Scope(ScopeInputShape::Singular) => {
            format!("{requirement} singular scope selector")
        }
        ParamShape::Scope(ScopeInputShape::Broad) => {
            format!("{requirement} singular or broad scope selector")
        }
        _ => format!("{requirement} custom scope parameter"),
    }
}

fn scope_fragment_label(fragment: ScopeFragment) -> &'static str {
    match fragment {
        ScopeFragment::ExactPathString => "canonical path string",
        ScopeFragment::Path => "path",
        ScopeFragment::CwdInferred => "cwd_inferred",
        ScopeFragment::Project => "project",
        ScopeFragment::Repo => "repo",
        ScopeFragment::Session => "session",
        ScopeFragment::Descendants => "descendants, subtree alias accepted",
        ScopeFragment::Set => "set",
        ScopeFragment::All => "all",
    }
}

fn is_broad_only(fragment: ScopeFragment) -> bool {
    matches!(
        fragment,
        ScopeFragment::Descendants | ScopeFragment::Set | ScopeFragment::All
    )
}

fn singular_scope_tool_names(tools: &[ToolContract]) -> Vec<&str> {
    tools
        .iter()
        .filter(|tool| {
            matches!(
                tool.param("scope").map(|param| &param.shape),
                Some(ParamShape::Scope(ScopeInputShape::Singular))
            )
        })
        .map(|tool| tool.name.as_str())
        .collect()
}

fn broad_scope_tool_names(tools: &[ToolContract]) -> Vec<&str> {
    tools
        .iter()
        .filter(|tool| {
            matches!(
                tool.param("scope").map(|param| &param.shape),
                Some(ParamShape::Scope(ScopeInputShape::Broad))
            )
        })
        .map(|tool| tool.name.as_str())
        .collect()
}

fn tools_with_names<'a>(tools: &'a [ToolContract], names: &[&str]) -> Vec<&'a str> {
    tools
        .iter()
        .filter(|tool| names.contains(&tool.name.as_str()))
        .map(|tool| tool.name.as_str())
        .collect()
}

fn inline_tool_list(tools: &[&str]) -> String {
    tools
        .iter()
        .map(|tool| format!("`{tool}`"))
        .collect::<Vec<_>>()
        .join(", ")
}

fn param_type_label(param: &ToolParamContract) -> String {
    if let Some(ev) = &param.enum_values {
        return format!("enum: {}", ev.join(" \\| "));
    }

    match &param.shape {
        ParamShape::Scalar(kind) => kind.clone(),
        ParamShape::Array { items } => match items {
            ArrayItems::Scalar(kind) => format!("array<{kind}>"),
            ArrayItems::ExchangeObject => "array<object>".to_string(),
        },
        ParamShape::Scope(_) | ParamShape::CustomSchema(_) => "string | object".to_string(),
    }
}
