use uuid::Uuid;

use crate::{
    CmError, Entry, EntryFilter, EntryKind, EntryRelation, NewEntry, NewScope, PagedResult,
    RelationKind, Scope, ScopeKind, ScopePath, StoreStats, UpdateEntry,
};

/// Synchronous storage interface for context entries.
///
/// All methods return `Result<T, CmError>`. The trait uses synchronous
/// signatures because cm-core has zero async dependencies. The adapter
/// crate (cm-store) wraps these in async methods using sqlx's internal
/// thread pool. A future rusqlite adapter would use
/// `tokio::task::spawn_blocking`.
///
/// ## Conventions
///
/// - Methods that query entries exclude superseded entries by default
///   unless the caller explicitly opts in via `EntryFilter::include_superseded`.
/// - Write methods (`create_entry`, `update_entry`, `supersede_entry`, `forget_entry`)
///   use the write pool (1 connection). Read methods use the read pool (4 connections).
/// - All IDs are UUIDv7, generated by the store on creation.
pub trait ContextStore {
    // ── Entry CRUD ──────────────────────────────────────────────

    /// Create a new entry.
    ///
    /// Generates a UUIDv7 `id`, computes the BLAKE3 `content_hash`,
    /// and sets `created_at` and `updated_at` to the current timestamp.
    ///
    /// # Errors
    ///
    /// - `CmError::ScopeNotFound` if `new_entry.scope_path` does not exist in `scopes`.
    /// - `CmError::DuplicateContent` if an active entry with the same content hash exists.
    /// - `CmError::Validation` if title or body is empty.
    fn create_entry(&self, new_entry: NewEntry) -> Result<Entry, CmError>;

    /// Retrieve a single entry by ID.
    ///
    /// Returns the entry regardless of superseded status.
    ///
    /// # Errors
    ///
    /// - `CmError::EntryNotFound` if no entry with this ID exists.
    fn get_entry(&self, id: Uuid) -> Result<Entry, CmError>;

    /// Retrieve multiple entries by IDs.
    ///
    /// Returns entries in the same order as the input IDs.
    /// Missing IDs are silently omitted from the result (no error).
    /// Returns entries regardless of superseded status.
    fn get_entries(&self, ids: &[Uuid]) -> Result<Vec<Entry>, CmError>;

    /// Resolve context for a scope by walking up the hierarchy.
    ///
    /// Returns all active entries from the target scope and every
    /// ancestor scope, ordered by:
    /// 1. Scope depth (most specific first)
    /// 2. `updated_at` DESC within each scope level
    ///
    /// This is the primary recall method. MCP tools call this to gather
    /// all relevant context for a given working scope.
    ///
    /// # Arguments
    ///
    /// - `scope_path`: The target scope to resolve from.
    /// - `kinds`: Optional filter to specific entry kinds. If empty, all kinds are included.
    /// - `limit`: Maximum total entries to return across all scope levels.
    fn resolve_context(
        &self,
        scope_path: &ScopePath,
        kinds: &[EntryKind],
        limit: u32,
    ) -> Result<Vec<Entry>, CmError>;

    /// Full-text search using FTS5.
    ///
    /// Searches `title` and `body` fields using SQLite FTS5 `MATCH` syntax.
    /// Results are ranked by FTS5 relevance score.
    ///
    /// # Arguments
    ///
    /// - `query`: FTS5 query string. Supports prefix queries (`rust*`),
    ///   phrase queries (`"scope path"`), and boolean operators (`AND`, `OR`, `NOT`).
    /// - `scope_path`: Optional scope filter. When set, only entries at this
    ///   exact scope or its ancestors are included.
    /// - `limit`: Maximum number of results.
    fn search(
        &self,
        query: &str,
        scope_path: Option<&ScopePath>,
        limit: u32,
    ) -> Result<Vec<Entry>, CmError>;

    /// Browse entries with filtering and pagination.
    ///
    /// Applies all filter criteria with AND semantics.
    /// Returns a paginated result set ordered by `updated_at DESC`.
    fn browse(&self, filter: EntryFilter) -> Result<PagedResult<Entry>, CmError>;

    /// Partially update an existing entry.
    ///
    /// Only fields set to `Some` in `update` are modified.
    /// If `body` or `kind` changes, the `content_hash` is recomputed
    /// and checked for duplicates.
    /// `updated_at` is refreshed by the database trigger.
    ///
    /// # Errors
    ///
    /// - `CmError::EntryNotFound` if the entry does not exist.
    /// - `CmError::DuplicateContent` if the updated content hash matches another active entry.
    fn update_entry(&self, id: Uuid, update: UpdateEntry) -> Result<Entry, CmError>;

    /// Supersede an entry: soft-delete the old entry and create a replacement.
    ///
    /// Sets `superseded_by` on `old_id` to the new entry's ID.
    /// Creates a `Supersedes` relation from the new entry to the old entry.
    /// Executed as a single transaction.
    ///
    /// # Errors
    ///
    /// - `CmError::EntryNotFound` if `old_id` does not exist.
    /// - `CmError::DuplicateContent` if the new entry's content hash matches another active entry.
    fn supersede_entry(&self, old_id: Uuid, new_entry: NewEntry) -> Result<Entry, CmError>;

    /// Soft-delete an entry by marking it as forgotten.
    ///
    /// Sets `superseded_by` to the entry's own ID (self-referential),
    /// distinguishing a "forgotten" entry from one superseded by a replacement.
    ///
    /// # Errors
    ///
    /// - `CmError::EntryNotFound` if the entry does not exist.
    fn forget_entry(&self, id: Uuid) -> Result<(), CmError>;

    // ── Relations ───────────────────────────────────────────────

    /// Create a relation between two entries.
    ///
    /// # Errors
    ///
    /// - `CmError::EntryNotFound` if either `source_id` or `target_id` does not exist.
    /// - `CmError::ConstraintViolation` if the relation already exists.
    fn create_relation(
        &self,
        source_id: Uuid,
        target_id: Uuid,
        relation: RelationKind,
    ) -> Result<EntryRelation, CmError>;

    /// Get all relations where the given entry is the source.
    fn get_relations_from(&self, source_id: Uuid) -> Result<Vec<EntryRelation>, CmError>;

    /// Get all relations where the given entry is the target.
    fn get_relations_to(&self, target_id: Uuid) -> Result<Vec<EntryRelation>, CmError>;

    // ── Scopes ──────────────────────────────────────────────────

    /// Create a new scope.
    ///
    /// Derives `kind` and `parent_path` from the scope path.
    /// The parent scope must already exist (except for `global`).
    ///
    /// # Errors
    ///
    /// - `CmError::ScopeNotFound` if the parent scope does not exist.
    /// - `CmError::ConstraintViolation` if the scope already exists.
    fn create_scope(&self, new_scope: NewScope) -> Result<Scope, CmError>;

    /// Retrieve a scope by its path.
    ///
    /// # Errors
    ///
    /// - `CmError::ScopeNotFound` if no scope with this path exists.
    fn get_scope(&self, path: &ScopePath) -> Result<Scope, CmError>;

    /// List all scopes, optionally filtered by kind.
    fn list_scopes(&self, kind: Option<ScopeKind>) -> Result<Vec<Scope>, CmError>;

    // ── Aggregation ─────────────────────────────────────────────

    /// Return aggregate statistics about the store.
    fn stats(&self) -> Result<StoreStats, CmError>;

    /// Export all active entries, optionally filtered by scope.
    ///
    /// Returns entries ordered by `scope_path ASC`, `created_at ASC`.
    /// Superseded entries are excluded.
    fn export(&self, scope_path: Option<&ScopePath>) -> Result<Vec<Entry>, CmError>;
}
