// AUTO-GENERATED by build.rs from tools.toml — do not edit
#![allow(dead_code, unused)]
#![allow(clippy::all)]
#[rustfmt::skip]
pub const RECALL_ABOUT: &str = "Search and retrieve context entries from the store.\n\nCombines FTS5 keyword search with hierarchical scope resolution. When no query is given, returns all entries visible at the target scope.";
#[rustfmt::skip]
pub const RECALL_QUERY_HELP: &str = "FTS5 search query (prefix: rust*, phrase: \"scope path\", boolean: AND/OR/NOT)";
#[rustfmt::skip]
pub const RECALL_SCOPE_HELP: &str = "Scope path (retrieves from this scope and ancestors). Default: global";
#[rustfmt::skip]
pub const RECALL_KINDS_HELP: &str = "Filter by entry kind (comma-separated). Valid: fact, decision, preference, lesson, reference, feedback, pattern, observation";
#[rustfmt::skip]
pub const RECALL_TAGS_HELP: &str = "Filter by tag (comma-separated, OR logic)";
#[rustfmt::skip]
pub const RECALL_LIMIT_HELP: &str = "Maximum number of results (default: 20, max: 200)";
#[rustfmt::skip]
pub const RECALL_MAX_TOKENS_HELP: &str = "Maximum token budget for response (trims results to fit)";

#[rustfmt::skip]
pub const STORE_ABOUT: &str = "Store a context entry.\n\nCreates a new entry with title, body, kind, and optional metadata. Scope chain is auto-created if missing. Use --supersedes to replace an existing entry.";
#[rustfmt::skip]
pub const STORE_TITLE_HELP: &str = "Entry title (short summary)";
#[rustfmt::skip]
pub const STORE_BODY_HELP: &str = "Entry body content (markdown)";
#[rustfmt::skip]
pub const STORE_KIND_HELP: &str = "Entry kind: fact, decision, preference, lesson, reference, feedback, pattern, observation";
#[rustfmt::skip]
pub const STORE_SCOPE_PATH_HELP: &str = "Target scope path (auto-created if missing). Default: global";
#[rustfmt::skip]
pub const STORE_CREATED_BY_HELP: &str = "Attribution (format: source_type:identifier). Default: agent:claude-code";
#[rustfmt::skip]
pub const STORE_TAGS_HELP: &str = "Tags for categorization (comma-separated)";
#[rustfmt::skip]
pub const STORE_CONFIDENCE_HELP: &str = "Confidence level: high, medium, low";
#[rustfmt::skip]
pub const STORE_SOURCE_HELP: &str = "Source URL or path (provenance)";
#[rustfmt::skip]
pub const STORE_EXPIRES_AT_HELP: &str = "Expiry timestamp (ISO 8601). Entry is considered stale after this time";
#[rustfmt::skip]
pub const STORE_PRIORITY_HELP: &str = "Numeric priority (higher = surfaces first)";
#[rustfmt::skip]
pub const STORE_SUPERSEDES_HELP: &str = "ID of entry to supersede (soft-deletes old, creates replacement)";

#[rustfmt::skip]
pub const DEPOSIT_ABOUT: &str = "Batch-store conversation exchanges.\n\nEach exchange becomes an observation entry. Provide an optional summary to create a linked summary entry.";
#[rustfmt::skip]
pub const DEPOSIT_EXCHANGES_HELP: &str = "JSON array of {user, assistant, title?} exchange objects";
#[rustfmt::skip]
pub const DEPOSIT_SUMMARY_HELP: &str = "Optional conversation summary (linked to exchanges)";
#[rustfmt::skip]
pub const DEPOSIT_SCOPE_PATH_HELP: &str = "Target scope path (auto-created if missing). Default: global";
#[rustfmt::skip]
pub const DEPOSIT_CREATED_BY_HELP: &str = "Attribution (format: source_type:identifier). Default: agent:claude-code";

#[rustfmt::skip]
pub const BROWSE_ABOUT: &str = "Browse entries with filtering and pagination.\n\nFor inventory and exploration. Returns metadata and snippet, not full body. Use cx_get for full content.";
#[rustfmt::skip]
pub const BROWSE_SCOPE_PATH_HELP: &str = "Filter to exact scope path (no ancestor walk)";
#[rustfmt::skip]
pub const BROWSE_KIND_HELP: &str = "Filter by kind: fact, decision, preference, lesson, reference, feedback, pattern, observation";
#[rustfmt::skip]
pub const BROWSE_TAG_HELP: &str = "Filter by tag (entries must have this tag)";
#[rustfmt::skip]
pub const BROWSE_CREATED_BY_HELP: &str = "Filter by creator (e.g. agent:claude-code, human:stuart)";
#[rustfmt::skip]
pub const BROWSE_INCLUDE_SUPERSEDED_HELP: &str = "Include superseded/forgotten entries (default: false)";
#[rustfmt::skip]
pub const BROWSE_LIMIT_HELP: &str = "Entries per page (default: 20, max: 200)";
#[rustfmt::skip]
pub const BROWSE_CURSOR_HELP: &str = "Pagination cursor from previous response";

#[rustfmt::skip]
pub const GET_ABOUT: &str = "Fetch full entry content by ID.\n\nReturns complete entries including body. Use after cx_recall or cx_browse for full content.";
#[rustfmt::skip]
pub const GET_IDS_HELP: &str = "Entry IDs to retrieve (space-separated, max 100)";

#[rustfmt::skip]
pub const UPDATE_ABOUT: &str = "Partially update an entry.\n\nOnly provided fields are modified. Changing body recomputes the content hash.";
#[rustfmt::skip]
pub const UPDATE_ID_HELP: &str = "Entry ID to update";
#[rustfmt::skip]
pub const UPDATE_TITLE_HELP: &str = "New title (omit to keep existing)";
#[rustfmt::skip]
pub const UPDATE_BODY_HELP: &str = "New body content (omit to keep existing). Recomputes content hash";
#[rustfmt::skip]
pub const UPDATE_KIND_HELP: &str = "New kind (omit to keep existing). Recomputes content hash";
#[rustfmt::skip]
pub const UPDATE_META_HELP: &str = "Replace metadata (JSON object with tags, confidence, source, expires_at, priority)";

#[rustfmt::skip]
pub const FORGET_ABOUT: &str = "Soft-delete entries.\n\nMarks entries as forgotten (sets superseded_by to own ID). Already-inactive entries are skipped.";
#[rustfmt::skip]
pub const FORGET_IDS_HELP: &str = "Entry IDs to forget (space-separated, max 100)";

#[rustfmt::skip]
pub const STATS_ABOUT: &str = "Show store statistics.\n\nDisplays entry counts by kind, scope, and tag, relation count, database size, and scope tree.";
#[rustfmt::skip]
pub const STATS_TAG_SORT_HELP: &str = "Tag sort order: name (alphabetical, default) or count (most used first)";

#[rustfmt::skip]
pub const EXPORT_ABOUT: &str = "Export entries and scopes as JSON.\n\nExports all active entries and scopes. Use --scope to filter to a subtree.";
#[rustfmt::skip]
pub const EXPORT_SCOPE_PATH_HELP: &str = "Filter to scope subtree (omit for full export)";
#[rustfmt::skip]
pub const EXPORT_FORMAT_HELP: &str = "Export format (currently only json). Default: json";
